<Project>
	<PropertyGroup>
		<AssemblyName>Norse.$(MSBuildProjectName)</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<NorseRefVersion>*-*</NorseRefVersion>
		<Nullable>enable</Nullable>
		<RootNamespace>Norse.$(MSBuildProjectName)</RootNamespace>
		<TargetFramework>net11.0</TargetFramework>
		<UseProjectReferences>true</UseProjectReferences>
	</PropertyGroup>
</Project>
