<Project Sdk="Aspire.AppHost.Sdk/13.5.1">

	<PropertyGroup>
		<AspireUseCliBundle>true</AspireUseCliBundle>
		<OutputType>Exe</OutputType>
		<UserSecretsId>norse-orchestration-apphost</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.*" />
		<ProjectReference Include="..\..\Yggdrasil\src\Hosting.Migrations.Service\Hosting.Migrations.Service.csproj" />
		<ProjectReference Include="..\..\Yggdrasil\src\Hosting.Stories.Server\Hosting.Stories.Server.csproj" />
		<ProjectReference Include="..\..\Yggdrasil\src\Hosting.Web.Server\Hosting.Web.Server.csproj" />
		<ProjectReference Include="..\..\Yggdrasil\src\Hosting.Worker\Hosting.Worker.csproj" />
	</ItemGroup>

</Project>
